# Generated by Django 4.2.3 on 2023-07-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inmueble', models.CharField(max_length=255)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direccion', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='fincas/')),
            ],
        ),
    ]
