# Generated by Django 4.2.3 on 2023-07-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0004_alter_finca_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=128)),
                ('admin', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
