# Generated by Django 4.2.3 on 2023-07-21 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0006_finca_cita'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finca',
            name='cita',
        ),
        migrations.AddField(
            model_name='cita',
            name='Finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finca.finca'),
        ),
    ]
