# Generated by Django 4.2.3 on 2023-07-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0003_cita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='imagen',
            field=models.URLField(),
        ),
    ]
